/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservationsystem;

import java.sql.*;
import javax.swing.*;
import java.util.*;



/**
 *
 * @author Nedlog
 */
public class SearchIntern extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public SearchIntern() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDestination = new javax.swing.JComboBox();
        cmbAirline = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        datepick2 = new org.netbeans.modules.form.InvalidComponent();
        jLabel6 = new javax.swing.JLabel();
        datepick1 = new org.netbeans.modules.form.InvalidComponent();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservationsystem/Golden Systems WEB.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 0, 420, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INDICATE YOUR ARRIVAL DATE");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 400, 280, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INDICATE YOUR DESTINATION");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 500, 240, 30);

        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dubai", "United States", "United Kingdom", "Canaga", "Chicago" }));
        getContentPane().add(cmbDestination);
        cmbDestination.setBounds(380, 500, 180, 30);

        cmbAirline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KLM", "Virgin Atlantic", "Qatar Airways" }));
        getContentPane().add(cmbAirline);
        cmbAirline.setBounds(380, 450, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INDICATE YOUR AIRLINE");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 450, 200, 30);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        getContentPane().add(btnBack);
        btnBack.setBounds(620, 560, 110, 40);

        datepick2.null;
        getContentPane().add(datepick2);
        datepick2.setBounds(380, 400, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INDICATE YOUR DEPARTURE DATE");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 350, 280, 30);

        datepick1.null;
        getContentPane().add(datepick1);
        datepick1.setBounds(380, 350, 200, 30);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(750, 560, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservationsystem/AeroflotAirHostesswallpaper_5_zps6c34b9ae.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datepick2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datepick2ActionPerformed

    }//GEN-LAST:event_datepick2ActionPerformed

    private void datepick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datepick1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datepick1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String departure=datepick1.getDate().toString().trim();
        String arrival=datepick2.getDate().toString().trim();
        String airline=cmbAirline.getSelectedItem().toString().trim();
        String destination=cmbDestination.getSelectedItem().toString().trim();
        if(departure.isEmpty()||arrival.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please all entries must be filled");
        }
        else{
            try{
                Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinebase", "root", "");
                Statement st=con.createStatement();
                String sql="SELECT * FROM availableflight";
                ResultSet rs=st.executeQuery(sql);
                while(rs.next()){
                    //for date
                    String flightNo=rs.getString("flightno");
                    String price=rs.getString("price");
                    String departureStored=rs.getDate("departure").toString().trim();
                    String arrivalStored=rs.getDate("arrival").toString().trim();
                    String destinationStored=rs.getString("destination").trim();
                    String airlineStored=rs.getString("airline").trim();
                    if((departureStored.equals(departure)&&arrivalStored.equals(arrival))||(destinationStored.equals(destination)&&airlineStored.equals(airline))){
                        String sql2="INSERT INTO searchavailable VALUES('"+flightNo+"','"+destinationStored+"','"+departureStored+"','"+arrivalStored+"','"+airlineStored+"','"+price+"')";
                        st.executeUpdate(sql2);
                        this.dispose();
                        Details obj=new Details();
                        obj.setSize(1000,680);
                        obj.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Sorry there are no available flights for your selection");
                    }
                    con.close();
                }

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchIntern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchIntern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchIntern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchIntern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchIntern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbAirline;
    private javax.swing.JComboBox cmbDestination;
    private org.netbeans.modules.form.InvalidComponent datepick1;
    private org.netbeans.modules.form.InvalidComponent datepick2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
